apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: webapp
    environment: test
spec:
  type: ClusterIP
  ports:
  # The Ingress/ALB will target.
  - port: 80 
    # This is the port the container is listening on.
    targetPort: 8080 
    protocol: TCP
    name: http
  selector:
    app: webapp