name: Run Docker Action from Subdirectory

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run My Docker Action
        uses: ./tasky-main/gh-actions # This points to the directory containing action.yml