name: Terrascan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files for debugging
        run: ls -R /github/workspace/
        
      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@v1.4.1
        with:
          iac_type: 'terraform' # Specify the IaC type. Other options include 'k8s' and 'helm'.
          iac_dir: 'purr-logic/web-app-infra'
          only_warn: false # This will cause the action to fail if violations are found.
          sarif_upload: true # Generate a SARIF file for GitHub Code Scanning.
          
      - name: Print SARIF file content
        run: cat terrascan.sarif
        continue-on-error: true #
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: terrascan.sarif
